export const MOCK_DB = {
  total: [
    {
      id: "TOTAL-1001",
      category: "통합",
      itemName: "서울 반도체",
      qty: 120,
      status: "정상",
      region: "SEOUL",
      periodType: "DAY",
      includeClosed: false,
    },
    {
      id: "TOTAL-1002",
      category: "통합",
      itemName: "부산 물류",
      qty: 450,
      status: "긴급",
      region: "BUSAN",
      periodType: "MONTH",
      includeClosed: true,
    },
    {
      id: "TOTAL-1003",
      category: "통합",
      itemName: "서울 전자",
      qty: 210,
      status: "검토중",
      region: "SEOUL",
      periodType: "DAY",
      includeClosed: false,
    },
  ],

  demand: [
    {
      id: "DEMAND-2001",
      category: "수요",
      itemName: "삼성전자",
      qty: 800,
      status: "정상",
      demandType: "NORMAL",
      customerName: "삼성",
    },
    {
      id: "DEMAND-2002",
      category: "수요",
      itemName: "LG 화학",
      qty: 230,
      status: "긴급",
      demandType: "URGENT",
      customerName: "LG",
    },
    {
      id: "DEMAND-2003",
      category: "수요",
      itemName: "현대 자동차",
      qty: 1200,
      status: "검토중",
      demandType: "NORMAL",
      customerName: "현대",
    },
  ],

  supply: [
    {
      id: "SUPPLY-3001",
      category: "공급",
      itemName: "1공장 CPU",
      qty: 999,
      status: "준비",
      factory: "F1",
      supplyStatus: "READY",
      onlyShortage: false,
      materialCode: "CPU",
    },
    {
      id: "SUPPLY-3002",
      category: "공급",
      itemName: "2공장 MEMORY",
      qty: 120,
      status: "완료",
      factory: "F2",
      supplyStatus: "DONE",
      onlyShortage: true,
      materialCode: "MEMORY",
    },
    {
      id: "SUPPLY-3003",
      category: "공급",
      itemName: "1공장 SSD",
      qty: 70,
      status: "준비",
      factory: "F1",
      supplyStatus: "READY",
      onlyShortage: true,
      materialCode: "SSD",
    },
  ],
};
